services:  
  mongo:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: "back-end"
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017
      DB_NAME: CrudApp
    depends_on:
      - mongo      

  frontend:
    build:
      context: ./frontend
    container_name: "front-end"
    ports:
      - "3000:3000"
    environment: 
      NEXT_PUBLIC_API: http://backend:5000/api
    depends_on:
      - backend

volumes:
  mongo-data:




